apiVersion: triggers.tekton.dev/v1alpha1
kind: TriggerBinding
metadata:
  name: github-pr-binding
spec:
  params:
    - name: gitrepositoryurl
      value: $(body.repository.ssh_url)
    - name: namespace
      value: default
    - name: gitrevision
      value: $(body.pull_request.head.sha)
