apiVersion: triggers.tekton.dev/v1alpha1
kind: TriggerTemplate
metadata:
  name: github-pr-pipeline-template
spec:
  params:
    - name: gitrevision
      description: The git revision (SHA)
      default: master
    - name: gitrepositoryurl
      description: The git repository url ("https://github.com/foo/bar.git")
    - name: namespace
      description: The namespace to create the resources
  resourcetemplates:
    - apiVersion: tekton.dev/v1beta1
      kind: PipelineRun
      metadata:
        generateName: github-pr-pipeline-run-
        namespace: $(tt.params.namespace)
      spec:
        pipelineRef:
          name: buildpacks
        params:
          - name: BUILDER_IMAGE
            value: docker.io/heroku/buildpacks:20@sha256:b9b1f20eb0f01c56803ef0463160acb646ede6cf6e8979f527adb0902679599f
          - name: TRUST_BUILDER
            value: "true"
          - name: APP_IMAGE
            value: ttl.sh/python-hello
          - name: imageUrl
            value: ttl.sh/python-hello
          - name: imageTag
            value: latest
          - name: SOURCE_URL
            value: $(tt.params.gitrepositoryurl)
          - name: SOURCE_REFERENCE
            value: $(tt.params.gitrevision)
          - name: SOURCE_SUBPATH
            value: ""
          - name: CACHE_IMAGE
            value: ttl.sh/python-hello-cache
        serviceAccountName: build-bot
        workspaces:
          - name: source-ws
            subPath: source
            persistentVolumeClaim:
              claimName: cache-image-pipelinerun-source-ws-pvc 
          - name: cache-ws
            emptyDir: {}
