apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  generateName: test-slack-pipeline-run-
  namespace: default
spec:
  pipelineRef:
    name: buildpacks-withstatus
  params:
    - name: BUILDER_IMAGE
      value: "docker.io/cnbs/sample-builder:bionic@sha256:6c03dd604503b59820fd15adbc65c0a077a47e31d404a3dcad190f3179e920b5"
    - name: TRUST_BUILDER
      value: "true"
    - name: APP_IMAGE
      value: ttl.sh/parthp/testingslack
    - name: SOURCE_URL
      value: https://github.com/buildpacks/samples
    - name: SOURCE_SUBPATH
      value: apps/ruby-bundler
  serviceAccountName: build-bot
  workspaces:
    - name: source-ws
      subPath: source
      persistentVolumeClaim:
        claimName: cache-image-pipelinerun-source-ws-pvc
    - name: cache-ws
      emptyDir: {}
    - name: status-ws
      emptyDir: {}
