apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: tkn-binding
  namespace: default
subjects:
  - kind: ServiceAccount
    name: build-bot
    namespace: default
roleRef:
  kind: Role
  name: tkn-role
  apiGroup: rbac.authorization.k8s.io
